name: CoreProtect-additions
main: com.alisaa.coreprotectadditions.Main
version: ${version}
api-version: 1.21.11
author: itsAlisaa
folia-supported: true
description: Provides logs for extra things, that CoreProtect hasn't implemented yet...
depend:
  - CoreProtect